CREATE TABLE USUARIOS(
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
user VARCHAR(30) NOT NULL UNIQUE,
pass VARCHAR(100) NOT NULL
)
ENGINE=InnoDb
CHARACTER SET latin1
COLLATE latin1_spanish_ci;

CREATE TABLE HISTORIA(
id INT(6) AUTO_INCREMENT NOT NULL,
id_usuario INT(6),
accion VARCHAR(100) NOT NULL,
tiempo VARCHAR(30) NOT NULL,
CONSTRAINT pk_usuario PRIMARY KEY(id),
CONSTRAINT fk_partidas_jugadas FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id)
)
ENGINE=InnoDb
CHARACTER SET latin1
COLLATE latin1_spanish_ci;